{% set name = "tinyrpc" %}
{% set version = "1.0.2" %}
{% set sha256 = "ca36a339de6e6129a0caa09fb9423937b8d7cab57a8fc040be0bf8fd6a2cf93a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script:
    - python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - six
  run:
    - python
    - six

test:
  imports:
    - tinyrpc
    - tinyrpc.dispatch
    - tinyrpc.protocols
    - tinyrpc.server
    - tinyrpc.transports

about:
  home: http://github.com/mbr/tinyrpc
  license: MIT
  summary: 'A small, modular, transport and protocol neutral RPC library that, among other things, supports JSON-RPC and zmq.'
  license_family: MIT
  # license_file: LICENSE # https://github.com/mbr/tinyrpc/pull/44
  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'

extra:
  recipe-maintainers:
    - mariusvniekerk
